[package]
name = "library_markketplace"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
library_markketplace = "0x0"
std = "0x1"
sui = "0x2"